### ISSUE TITLE
Apparent Bug in 06-deferred-steps.ts

### ISSUE THREAD

**Issue by king612** [danielgerlag/workflow-es#36]
I'm sorry I can't post the entire stack trace - I work on a closed system...

Running 06-deferred-steps.ts in VS Code:

```Error executing workflow...  on Step 1 - {
   Error: the number of constructor arguments in in the derived class bodyClass must be >= than [sic] the number of constructor arguments of its base class.
   at /....../node_modules/inversify/lib/planning/planner.js:111:27
    :
```

**Comment by king612** [comment]
02-hello-world.ts  also fails with same error.  

But all the rest of the samples worked for me.  

(I'm only looking at TypeScript ones)

**Comment by danielgerlag** [comment]
I can't reproduce this... what versions of Node.js and Typescript are you using?
Also, if you're just running the samples... surely the stack trace should not contain anything sensitive?

**Comment by king612** [comment]
I'm running on Node 10.13, TS ^3.4.1.

It's not a sensitivity issue, it runs on an air-gapped system.  I can't just cut and paste it - I'd literally have to retype the whole thing.  (Makes working with open source projects a hassle, believe me, I know).

Let me try to provide more detail, but be aware this is rekeyed from the real stack trace so....

as posted before, the stack trace begins with:
Error: the number of constructor arguments in in the derived class bodyClass must be >= than [sic] the number of constructor arguments of its base class.
   at /....../node_modules/inversify/lib/planning/planner.js:111:27

Followed by (abbreviated):

at Array.forEach
at _createSubRequests ... inversify/lib/planning/planner.js:94:20
at Object.plan .... inversify/lib/planning/planner.js:136:9
at  inversify/lib/container/container.js:317:37
... more lines from Container
at  .... workflow-executor.js:92:65
at ....several more lines from executor (step, Object, step, Object..)
at NewPromise (<anonymous>)
at __awaiter
  ...
at workflow-queue-worker.js:117:60
... more queue worker lines...  WorkflowQueueWorker, step, Object.next, fulfilled)

It looks like at the node_modules level, the version of inversify that got installed looks to be 4.14.0


Hope this helps.  --jfk

**Comment by jan-kacina** [comment]
Any news on this issue? I am facing the same error within pure JS (without TS).
The problem is related to `thenRun `method (inline step) - when it is removed, workflow has finished successfully.

Thanks,
Jan

**Comment by iakshay** [comment]
Same issue when trying with Node 18 and typescript 4.8.4. Perhaps related to https://github.com/inversify/InversifyJS/issues/522
